/* Build-time generator for primes.ispc: writes primes_tables.h to stdout.
 *
 * Everything here depends only on the primes below a fixed bound, never on the sieve size, and
 * the program still sieves every pass from scratch. The tables replace arithmetic that each pass
 * used to repeat:
 *   - TAB_SB:   for each prime 17 <= p < LIMIT, its first bit at or after p*p in each of the
 *               8 planes, stored as an offset from p*p/30 (fits 16 bits).
 *   - PAT_*:    for each prime 17 <= p < 1024, the stride-p word pattern shared by all 8 planes
 *               (period L, extended by 32 words) and its phase at the start word in each plane.
 *   - TILE/P13: the 7x11 wheel tile of each plane and 13's pattern with its phase per plane.
 * Primes at or above LIMIT (sizes above LIMIT^2) fall back to the run-time start_bit().
 *
 * Usage: gen_tables [LIMIT]   (default 10000 = sqrt(10^8); 1024 <= LIMIT <= 65536)
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

#define MAXPAT 1024 /* must match primes.ispc */
#define EXT 32      /* words past each period: the largest STEP of any target */

static const unsigned RES[8] = {1, 7, 11, 13, 17, 19, 23, 29};
static const unsigned INV30[30] = {0,1,0,0,0,0,0,13,0,0,0,11,0,7,0,0,0,23,0,19,
                                   0,0,0,17,0,0,0,0,0,29};

static unsigned start_bit(unsigned p, unsigned R, unsigned kmin) {
    unsigned kr = (R * INV30[p % 30]) % 30;
    unsigned k = kmin + (kr + 30 - kmin % 30) % 30;
    return (p * k - R) / 30;
}

/* period of a pattern: a multiple of p that is at least EXT words */
static unsigned period(unsigned p) { unsigned L = p; while (L < EXT) L += p; return L; }

/* base pattern of p into pat[0 .. L+EXT), tab[t] = word whose bit t is set */
static void pattern(unsigned p, uint64_t *pat, unsigned *tab) {
    unsigned L = period(p);
    memset(pat, 0, sizeof(uint64_t) * (L + EXT));
    for (unsigned j = 0; j < (p << 6); j += p) {
        pat[j >> 6] |= (uint64_t)1 << (j & 63);
        tab[j & 63] = j >> 6;
    }
    for (unsigned k = p; k < L + EXT; k++) pat[k] = pat[k - p];
}

static void words(const uint64_t *w, unsigned n) {
    for (unsigned k = 0; k < n; k++)
        printf("0x%016llxull,%s", (unsigned long long)w[k], (k % 4 == 3) ? "\n" : "");
}

int main(int argc, char **argv) {
    unsigned limit = argc > 1 ? (unsigned)atoi(argv[1]) : 10000;
    if (limit < MAXPAT || limit > 65536) { fprintf(stderr, "bad LIMIT\n"); return 1; }
    char *comp = calloc(limit, 1);
    for (unsigned i = 2; i * i < limit; i++)
        if (!comp[i]) for (unsigned j = i * i; j < limit; j += i) comp[j] = 1;
    unsigned *pr = malloc(sizeof(unsigned) * limit), np = 0, nd = 0;
    for (unsigned c = 17; c < limit; c++) if (!comp[c]) { pr[np++] = c; if (c < MAXPAT) nd++; }

    printf("// Generated by gen_tables.c at build time. Do not edit.\n");
    printf("#define TAB_N %u      // primes 17 <= p < %u with tabled start bits\n", np, limit);
    printf("#define TAB_ND %u     // primes 17 <= p < %u with tabled patterns\n", nd, MAXPAT);
    printf("#define TAB_EXT %u\n#define TAB_MAXPAT %u\n", EXT, MAXPAT);

    printf("static const uniform uint16 TAB_SB[%u][8] = {\n", np);
    for (unsigned i = 0; i < np; i++) {
        unsigned p = pr[i], base = p * p / 30;
        printf("{");
        for (int pl = 0; pl < 8; pl++) {
            unsigned d = start_bit(p, RES[pl], p) - base;
            if (d > 65535) { fprintf(stderr, "overflow\n"); return 1; }
            printf("%u%s", d, pl < 7 ? "," : "");
        }
        printf("},\n");
    }
    printf("};\n");

    /* Pattern words. Row 0 is an all-zero pattern (period EXT) for unused group members. */
    uint64_t *pat = malloc(sizeof(uint64_t) * (2 * MAXPAT + 2 * EXT));
    unsigned tab[64];
    unsigned off = 2 * EXT, *offs = malloc(sizeof(unsigned) * nd);
    for (unsigned i = 0; i < nd; i++) { offs[i] = off; off += period(pr[i]) + EXT; }
    printf("static const uniform uint32 PAT_OFF[%u] = {", nd);
    for (unsigned i = 0; i < nd; i++) printf("%u,", offs[i]);
    printf("};\nstatic const uniform uint16 PAT_L[%u] = {", nd);
    for (unsigned i = 0; i < nd; i++) printf("%u,", period(pr[i]));
    printf("};\nstatic const uniform uint16 PAT_PH[%u][8] = {\n", nd);
    for (unsigned i = 0; i < nd; i++) {
        pattern(pr[i], pat, tab);
        printf("{");
        for (int pl = 0; pl < 8; pl++)
            printf("%u%s", tab[start_bit(pr[i], RES[pl], pr[i]) & 63], pl < 7 ? "," : "");
        printf("},\n");
    }
    printf("};\nstatic const uniform uint64 PAT[%u] = {\n", off);
    memset(pat, 0, sizeof(uint64_t) * 2 * EXT);
    words(pat, 2 * EXT);
    for (unsigned i = 0; i < nd; i++) { pattern(pr[i], pat, tab); words(pat, period(pr[i]) + EXT); }
    printf("};\n");

    /* Wheel tile: multiples of 7 or 11 (from 7 and 11 themselves), one 77-word period per plane. */
    printf("static const uniform uint64 TILE[8][%u] = {\n", 77 + EXT);
    for (int pl = 0; pl < 8; pl++) {
        uint64_t t[77 + EXT];
        memset(t, 0, sizeof t);
        for (unsigned m = 0; m < 77 * 64; m++) {
            unsigned n = 30 * m + RES[pl];
            if (n % 7 == 0 || n % 11 == 0) t[m >> 6] |= (uint64_t)1 << (m & 63);
        }
        for (unsigned k = 77; k < 77 + EXT; k++) t[k] = t[k - 77];
        printf("{\n"); words(t, 77 + EXT); printf("},\n");
    }
    printf("};\n");

    /* 13: base pattern and its phase at word 0 of each plane. */
    unsigned L13 = period(13);
    pattern(13, pat, tab);
    printf("#define P13_L %u\nstatic const uniform uint64 P13[%u] = {\n", L13, L13 + EXT);
    words(pat, L13 + EXT);
    printf("};\nstatic const uniform uint16 P13_PH[8] = {");
    for (int pl = 0; pl < 8; pl++) {
        unsigned b = start_bit(13, RES[pl], 13);
        int r = (int)tab[b & 63] - (int)((b >> 6) % L13);
        printf("%d,", r < 0 ? r + (int)L13 : r);
    }
    printf("};\n");
    return 0;
}
